# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKGHN94kwnpnNjusVcOi5Wtl_TrTIQSh

✅ Task 1: Simple Python Calculator (Sum of Two Numbers)
"""

# Simple Calculator to Add Two Numbers

# Input from user
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

# Calculate sum
sum_result = num1 + num2

"""✅ Task 2: Simple Python Grading System"""

# Simple Grading System

# Input marks from user
marks = float(input("Enter your marks (out of 100): "))

# Determine grade using if-else
if marks >= 90:
    grade = "A+"
elif marks >= 80:
    grade = "A"
elif marks >= 70:
    grade = "B"
elif marks >= 60:
    grade = "C"
elif marks >= 50:
    grade = "D"
else:
    grade = "F (Fail)"

"""Create three different strings"""

